In [2]:
import sympy
s = sympy.symbols('x:11')
s

(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10)

## Chapter 6 - Problems

# 1). 
### Plot the graph of


$$
\begin{aligned}
& x(t)=4 \cos (-11 t / 4)+7 \cos (t) \\
& y(t)=4 \sin (-11 t / 4)+7 \sin (t)
\end{aligned}
$$

for $0 \leq t \leq 14 \pi$.

# 2. 
### Plot the graph of


$$
\begin{aligned}
& x(t)=\cos (t)+1 / 2 \cos (7 t)+1 / 3 \sin (17 t) \\
& y(t)=\sin (t)+1 / 2 \sin (7 t)+1 / 3 \cos (17 t)
\end{aligned}
$$

for $0 \leq t \leq 14 \pi$.

# 3. 
### Consider the following function.haviour.

$$
f(x):=\sum_{k=1}^{100}\left(\frac{\sin \left(2 \pi k^{2} x\right)}{4 \pi^{2} k^{5}}+\frac{x^{2}}{2 k}\right)
$$

This function was suggested by Sungkon Chang as an example of a function that looks quite "innocent" but whose derivatives behave quite wildly. Plot $f(x)$, $f^{\prime}(x)$ and $f^{\prime \prime}(x)$ and observe this behaviour.

# 4. 
### Consider the following functions of two variablesu, v)=\frac{3}

$$
\begin{aligned}
& \mathbf{x}(u, v)=\sin (v) \cos (u) \\
& \mathbf{y}(u, v)=\sin (v) \sin (u) \\
& \mathbf{z}(u, v)=\cos (v)
\end{aligned}
$$

Generate the surface $(\mathbf{x}, \mathbf{y}, \mathbf{z})$ when $0 \leq u \leq 3 \pi / 2$ and $0 \leq v \leq \pi$.

Now consider 
$$
\mathbf{x}{1}(u, v)=\frac{-3}{8} \cos (v) \sin \left(\frac{4 u}{3}\right), \mathbf{y}{\mathbf{1}}(u, v)=\frac{3}
$$

${8} \cos \left(\frac{4 u}{3}\right) \cos (v)$ and $\mathbf{z}_{\mathbf{1}}(u, v)=\frac{\sin (v)}{2}$. Generate the surface


$$
\left(\frac{\mathrm{d} \mathbf{x}_{1}}{\mathrm{~d} v \mathrm{~d} u}, \frac{\mathrm{d} \mathbf{y}_{1}}{\mathrm{~d} u \mathrm{~d} v}, \frac{\mathrm{d} \mathbf{z}_{1}}{\mathrm{~d} v}\right)
$$


when $0 \leq u \leq 3 \pi / 2$ and $0 \leq v \leq \pi$. Finally, superimpose these two images.

# 5. 
### Consider the function 
$\cos \left(x^{2}\right)$. Calculate the area below this function and between 0 and where the function first hits the $x$-axis.

# 6. 
### Write a function to check that, for any $n$, the following identity holds:


$$
\operatorname{det}\left(\begin{array}{ccccc}
x & a_{1} & a_{2} & \cdots & a_{n} \\
a_{1} & x & a_{2} & \cdots & a_{n} \\
a_{1} & a_{2} & x & \cdots & a_{n} \\
\vdots & \vdots & \vdots & & \vdots \\
a_{1} & a_{2} & a_{3} & \cdots & x
\end{array}\right)=\left(x+a_{1}+\cdots+a_{n}\right)\left(x-a_{1}\right) \cdots\left(x-a_{n}\right)
$$

# 7. 
### Write a function to check that, for any $n$, the following identity holds:


$$
\operatorname{det}\left(\begin{array}{cccccc}
1 & 1 & 1 & \cdots & 1 & 1 \\
b_{1} & a_{1} & a_{1} & \cdots & a_{1} & a_{1} \\
b_{1} & b_{2} & a_{2} & \cdots & a_{2} & a_{2} \\
\vdots & \vdots & \vdots & & \vdots & \vdots \\
b_{1} & b_{2} & b_{3} & \cdots & b_{n} & a_{n}
\end{array}\right)=\left(a_{1}-b_{1}\right)\left(a_{2}-b_{2}\right) \cdots\left(a_{n}-b_{n}\right)
$$

# 8. 
The Hilbert matrix is a square matrix whose element in row $i$ and column $j$ is $\frac{1}{i+j-1}$. Construct the Hilbert matrix of order 6 (i.e. a $6 \times 6$-matrix) and compute its determinant and its inverse. Try this for $7 \times 7$ and $8 \times 8$ matrices. Construct a table which shows the determinant of Hilbert matrices of orders 1 through 10.

# 9. 
Construct a $10 \times 10$ upper triangular matrix $A$ (see Wikipedia for the definition of such matrices) whose nonzero entries are random integers. Show that its determinant is equal to the product of the entries on its main diagonal. Now consider the transpose matrix $A^{t}$ and show that its determinant $\left(\operatorname{det}\left(A^{t}\right)\right)$ is the same as $A$. What is $\operatorname{det}\left(A+A^{t}\right)$ ?

In [14]:
import numpy as np
import math
#help(np.triu)

In [53]:
# create a 10x10 array with random numbers, each with a value between 1 and 100
arrayA = np.random.randint(low=-10, high=10, size=(10, 10))
print(arrayA)

[[ -8  -8 -10   6   1 -10   8   7   4  -3]
 [  7   6  -8   0   7  -8  -7  -5   7   9]
 [  3  -2  -5  -4  -7   9  -5   6   6 -10]
 [  2  -1   5   4  -9   7   3  -3  -6   7]
 [ -1  -3  -4  -8 -10  -4   8  -4  -6  -8]
 [  3  -8   6  -8  -7   1 -10  -4   1   0]
 [ -4   5   2 -10  -6   3  -6  -5   6  -2]
 [  7   3   9  -2   2   3  -7   5   1   2]
 [ -1   7 -10 -10  -9  -2  -8  -5   2   5]
 [ -6   2   0   5   1   6  -2   5   4  -8]]


In [54]:
# Generate a 10x10 upper triangular matrix with random nonzero integers
A = np.triu(arrayA)
print(A)

[[ -8  -8 -10   6   1 -10   8   7   4  -3]
 [  0   6  -8   0   7  -8  -7  -5   7   9]
 [  0   0  -5  -4  -7   9  -5   6   6 -10]
 [  0   0   0   4  -9   7   3  -3  -6   7]
 [  0   0   0   0 -10  -4   8  -4  -6  -8]
 [  0   0   0   0   0   1 -10  -4   1   0]
 [  0   0   0   0   0   0  -6  -5   6  -2]
 [  0   0   0   0   0   0   0   5   1   2]
 [  0   0   0   0   0   0   0   0   2   5]
 [  0   0   0   0   0   0   0   0   0  -8]]


In [55]:
# get the determinant, numpy's linear algebra extention method to find determinant of a square matrix
det_A = np.linalg.det(A)
print(det_A)

-4607999.999999997


In [67]:
# extract the entries on matrix A's main diagonal
diagonal_entries = np.diag(A)

# then find the product of A's main diagonal
print(np.prod(diagonal_entries))

-4608000


In [66]:
# to get the transpose of a np matrix, you can just do <theMatrix>.T
A_T = A.T
print(A_T)

[[ -8   0   0   0   0   0   0   0   0   0]
 [ -8   6   0   0   0   0   0   0   0   0]
 [-10  -8  -5   0   0   0   0   0   0   0]
 [  6   0  -4   4   0   0   0   0   0   0]
 [  1   7  -7  -9 -10   0   0   0   0   0]
 [-10  -8   9   7  -4   1   0   0   0   0]
 [  8  -7  -5   3   8 -10  -6   0   0   0]
 [  7  -5   6  -3  -4  -4  -5   5   0   0]
 [  4   7   6  -6  -6   1   6   1   2   0]
 [ -3   9 -10   7  -8   0  -2   2   5  -8]]


In [70]:
# to get |A_T|, we can use numpy's linear algebra extention method to find determinant of a square matrix again
det_A_T = np.linalg.det(A_T)
print(det_A_T)

-4607999.999999997


In [71]:
# Matrix addition is scalar or elementwise, ie. A[n][m] + B[n][m]
AplusA_T = np.add(A, A_T)
print(AplusA_T)

[[-16  -8 -10   6   1 -10   8   7   4  -3]
 [ -8  12  -8   0   7  -8  -7  -5   7   9]
 [-10  -8 -10  -4  -7   9  -5   6   6 -10]
 [  6   0  -4   8  -9   7   3  -3  -6   7]
 [  1   7  -7  -9 -20  -4   8  -4  -6  -8]
 [-10  -8   9   7  -4   2 -10  -4   1   0]
 [  8  -7  -5   3   8 -10 -12  -5   6  -2]
 [  7  -5   6  -3  -4  -4  -5  10   1   2]
 [  4   7   6  -6  -6   1   6   1   4   5]
 [ -3   9 -10   7  -8   0  -2   2   5 -16]]


What is $\operatorname{det}\left(A+A^{t}\right)$ ?

In [72]:
det_AplusA_T = np.linalg.det(AplusA_T)
print(det_AplusA_T)

-4714542862485.02


For a 3x3 matrix

$$
[ \text{det}(A) = 
\begin{vmatrix} 
a & b & c \\ d & e & f \\ g & h & i \end{vmatrix} = aei + bfg + cdh - afh - bdi - ceg ]
$$

# 10. 
Investigate how many solutions the equation $\sin \left(x^{2}\right)-\cos \left(x^{3}\right)=0$ has for $0 \leq x \leq \pi$.

# 11. 
Plot the graphs of the functions $2 \exp \left(-x^{2}\right)$ and $\cos (\sin (x)+\cos (x))$ between $[-\pi, \pi]$. Investigate where they intersect.

# 12. 
Define the functions


$$
\begin{gathered}
f(t, a)=2+\frac{1}{2} \sin (a t) \\
g(t, b, c)=\cos \left(t+\frac{\sin (b t)}{c}\right) \\
h(t, b, c)=\sin \left(t+\frac{\sin (b t)}{c}\right)
\end{gathered}
$$


Generate the parametric graph


$$
\begin{aligned}
& x(t)=f(t, 8) g(t, 16,4) \\
& y(t)=f(t, 8) h(t, 16,4)
\end{aligned}
$$


when $0 \leq t \leq 2 \pi$. Also plot the graph


$$
(f(t, 6) g(t, 18,18), f(t, 6) h(t, 18,18))
$$


when $0 \leq t \leq 2 \pi$.

# 13. 
Let $g(x)=\sin (x)+\cos (x)$. Plot graphs of $g(g(g(g(x))))$ and $g(g(g(g(g(x)))))$ for $x$ lying between 0 and $\pi$. There are four points where the graphs cross. Find, numerically, their $(x, y)$ coordinates.

# 14. 
Let $A$ denote the $3 \times 3$ matrix


$$
\left(\begin{array}{lll}
x+y & x^{2}+y & x^{3}+y \\
x+y^{2} & x^{2}+y^{2} & x^{3}+y^{2} \\
x^{2}+y^{3} & x^{2}+y^{3} & x^{3}+y^{3}
\end{array}\right)
$$


(yes, the fact that the bottom left-hand entry does not fit the pattern of the rest of the entries is intended!) and let $B$ denote its inverse. Show that the sum of the entries in the first row of $B$ is 0 . What is the sum of the entries in each of the second and third rows? Also find the sum of the entries in each column of $B$.

# 15. 
Investigate and determine the values of $x$ between $0 \leq x \leq 2 \pi$ such that we have the inequality

$$
2 \cos (x) \leq \sqrt{1+\sin (2 x)}-\sqrt{1-\sin (2 x)} \leq \sqrt{2}
$$