# chapter 6
## Problem 9. 
Construct a $10 \times 10$ upper triangular matrix $A$ (see Wikipedia for the definition of such matrices) whose nonzero entries are random integers. 

Show that its determinant is equal to the product of the entries on its main diagonal. 

Now consider the transpose matrix $A^{t}$ and show that its determinant $\left(\operatorname{det}\left(A^{t}\right)\right)$ is the same as $A$. 

What is $\operatorname{det}\left(A+A^{t}\right)$ ?

In [8]:
import numpy as np

In [16]:
arrayA = np.random.randint(low=-10, high=10, size=(10,10))
arrayA

array([[ -3,   7,  -6,   4,   6,  -5,  -4,  -4,   7,   0],
       [  9,   5,  -8,   4,   7,   3,  -6,  -5,   0,   1],
       [ -4,   7,  -7,  -1,  -4,   7,   4,  -6,   4,   3],
       [ -4,   5,  -9,  -9,  -7,   5,  -8,   0,  -3,  -9],
       [ -8,   2,   5,   4,  -4,  -8,   3,   3,  -6,   6],
       [ -4,  -2,   1,  -1,  -7,   8,  -3,  -5,   3,   7],
       [  0,  -7,  -5,  -4,   4,   9,  -2,  -9, -10,  -5],
       [  7,   4,  -5,   7,   6,  -5,  -7,  -7,   3,  -1],
       [ -1,   6,   3,   4,   4,  -2,   7,  -4,   8,   3],
       [  5,  -9,  -1,   4,  -2,   8,  -2, -10,   9,  -6]])

In [18]:
A = np.triu(arrayA)
print(A)

[[ -3   7  -6   4   6  -5  -4  -4   7   0]
 [  0   5  -8   4   7   3  -6  -5   0   1]
 [  0   0  -7  -1  -4   7   4  -6   4   3]
 [  0   0   0  -9  -7   5  -8   0  -3  -9]
 [  0   0   0   0  -4  -8   3   3  -6   6]
 [  0   0   0   0   0   8  -3  -5   3   7]
 [  0   0   0   0   0   0  -2  -9 -10  -5]
 [  0   0   0   0   0   0   0  -7   3  -1]
 [  0   0   0   0   0   0   0   0   8   3]
 [  0   0   0   0   0   0   0   0   0  -6]]


In [20]:
det_A = np.linalg.det(A)
print(det_A)

-20321280.000000034


In [24]:
diagonal_entries = np.diag(A)
print(diagonal_entries)

productOfDiagonalEntries = np.prod(diagonal_entries)
print(productOfDiagonalEntries)

[-3  5 -7 -9 -4  8 -2 -7  8 -6]
-20321280


In [28]:
round(det_A,3) == round(productOfDiagonalEntries,3)

True

In [30]:
A_T = A.T
print(A_T)

[[ -3   0   0   0   0   0   0   0   0   0]
 [  7   5   0   0   0   0   0   0   0   0]
 [ -6  -8  -7   0   0   0   0   0   0   0]
 [  4   4  -1  -9   0   0   0   0   0   0]
 [  6   7  -4  -7  -4   0   0   0   0   0]
 [ -5   3   7   5  -8   8   0   0   0   0]
 [ -4  -6   4  -8   3  -3  -2   0   0   0]
 [ -4  -5  -6   0   3  -5  -9  -7   0   0]
 [  7   0   4  -3  -6   3 -10   3   8   0]
 [  0   1   3  -9   6   7  -5  -1   3  -6]]


In [34]:
det_A_T = np.linalg.det(A_T)
print(round(det_A_T,3))

-20321280.0


In [36]:
round(det_A_T,3) == round(det_A,3)

True

In [38]:
#what is the |A + A_T|
# A[n][m] + B[n][m]

In [40]:
AplusA_T = np.add(A, A_T)
print(AplusA_T)

[[ -6   7  -6   4   6  -5  -4  -4   7   0]
 [  7  10  -8   4   7   3  -6  -5   0   1]
 [ -6  -8 -14  -1  -4   7   4  -6   4   3]
 [  4   4  -1 -18  -7   5  -8   0  -3  -9]
 [  6   7  -4  -7  -8  -8   3   3  -6   6]
 [ -5   3   7   5  -8  16  -3  -5   3   7]
 [ -4  -6   4  -8   3  -3  -4  -9 -10  -5]
 [ -4  -5  -6   0   3  -5  -9 -14   3  -1]
 [  7   0   4  -3  -6   3 -10   3  16   3]
 [  0   1   3  -9   6   7  -5  -1   3 -12]]


In [42]:
det_AplusA_T = np.linalg.det(AplusA_T)
print(det_AplusA_T)

149308468886.99893
