# chapter 6
## 9. 
Construct a $10 \times 10$ upper triangular matrix $A$ (see Wikipedia for the definition of such matrices) whose nonzero entries are random integers. Show that its determinant is equal to the product of the entries on its main diagonal. Now consider the transpose matrix $A^{t}$ and show that its determinant $\left(\operatorname{det}\left(A^{t}\right)\right)$ is the same as $A$. What is $\operatorname{det}\left(A+A^{t}\right)$ ?

In [1]:
import numpy as np
import math
#help(np.triu)

In [2]:
# create a 10x10 array with random numbers, each with a value between 1 and 100
arrayA = np.random.randint(low=-10, high=10, size=(10, 10))
print(arrayA)

[[  4   7   2  -8  -9  -2   0  -5   0  -3]
 [ -1   6 -10  -3 -10  -9   1  -9   0   2]
 [ -9  -3  -6  -5   0  -5  -3  -1  -2  -4]
 [ -5  -6  -8  -2  -3   2   3  -2  -1  -4]
 [ -1  -9   1  -3   5  -4   5  -9  -7   3]
 [  6   3  -1   6   8  -9   0  -4   1  -9]
 [-10  -2 -10 -10  -1 -10  -1  -9  -8   7]
 [  9  -2  -4   7   7  -9   9 -10   1 -10]
 [ -3   6   3   3 -10   8  -7   9   3 -10]
 [  8   7  -3  -7  -8   5  -8  -9   9   3]]


In [3]:
# Generate a 10x10 upper triangular matrix with random nonzero integers
A = np.triu(arrayA)
print(A)

[[  4   7   2  -8  -9  -2   0  -5   0  -3]
 [  0   6 -10  -3 -10  -9   1  -9   0   2]
 [  0   0  -6  -5   0  -5  -3  -1  -2  -4]
 [  0   0   0  -2  -3   2   3  -2  -1  -4]
 [  0   0   0   0   5  -4   5  -9  -7   3]
 [  0   0   0   0   0  -9   0  -4   1  -9]
 [  0   0   0   0   0   0  -1  -9  -8   7]
 [  0   0   0   0   0   0   0 -10   1 -10]
 [  0   0   0   0   0   0   0   0   3 -10]
 [  0   0   0   0   0   0   0   0   0   3]]


In [4]:
# get the determinant, numpy's linear algebra extention method to find determinant of a square matrix
det_A = np.linalg.det(A)
print(det_A)

-1166399.999999999


In [12]:
# extract the entries on matrix A's main diagonal
diagonal_entries = np.diag(A)

# then find the product of A's main diagonal
productOfDiagonalEntries = np.prod(diagonal_entries)
print(productOfDiagonalEntries)

-1166400


In [6]:
# to get the transpose of a np matrix, you can just do <theMatrix>.T
A_T = A.T
print(A_T)

[[  4   0   0   0   0   0   0   0   0   0]
 [  7   6   0   0   0   0   0   0   0   0]
 [  2 -10  -6   0   0   0   0   0   0   0]
 [ -8  -3  -5  -2   0   0   0   0   0   0]
 [ -9 -10   0  -3   5   0   0   0   0   0]
 [ -2  -9  -5   2  -4  -9   0   0   0   0]
 [  0   1  -3   3   5   0  -1   0   0   0]
 [ -5  -9  -1  -2  -9  -4  -9 -10   0   0]
 [  0   0  -2  -1  -7   1  -8   1   3   0]
 [ -3   2  -4  -4   3  -9   7 -10 -10   3]]


In [7]:
# to get |A_T|, we can use numpy's linear algebra extention method to find determinant of a square matrix again
det_A_T = np.linalg.det(A_T)
print(det_A_T)

-1166400.000000003


What is $\operatorname{det}\left(A+A^{t}\right)$ ?

In [10]:
# Matrix addition is scalar or elementwise, ie. A[n][m] + B[n][m]
AplusA_T = np.add(A, A_T)
print(AplusA_T)

[[  8   7   2  -8  -9  -2   0  -5   0  -3]
 [  7  12 -10  -3 -10  -9   1  -9   0   2]
 [  2 -10 -12  -5   0  -5  -3  -1  -2  -4]
 [ -8  -3  -5  -4  -3   2   3  -2  -1  -4]
 [ -9 -10   0  -3  10  -4   5  -9  -7   3]
 [ -2  -9  -5   2  -4 -18   0  -4   1  -9]
 [  0   1  -3   3   5   0  -2  -9  -8   7]
 [ -5  -9  -1  -2  -9  -4  -9 -20   1 -10]
 [  0   0  -2  -1  -7   1  -8   1   6 -10]
 [ -3   2  -4  -4   3  -9   7 -10 -10   6]]


In [11]:
det_AplusA_T = np.linalg.det(AplusA_T)
print(det_AplusA_T)

-9175741420.000002
